# TP 1: Linear algebra

## Recalls

##### Matrix and vector creation
Vectors and matrices in Python can be defined manually using Numpy arrays:

In [1]:
import numpy as np

In [2]:
# Define a vector
x = np.array([4, 6, -1])
print(x)

[ 4  6 -1]


In [3]:
# Dimension
print(x.shape)

# Number of elements
print(x.size)

(3,)
3


In [4]:
# Define a matrix
A = np.array([[1, 3, 7], [8, 4, 5]])
print(A)

[[1 3 7]
 [8 4 5]]


In [5]:
# Dimension
print(A.shape)

(2, 3)


In [6]:
# Number of elements
print(A.size)

6


In [7]:
# Type of elements
A.dtype

dtype('int64')

The type can be changed a posteriori using ```asarray```:

In [8]:
A = A.astype('int32')
A.dtype

dtype('int32')

The type can be set when creating the matrix:

In [9]:
A = np.array([[1, 3, 7], [8, 4, 5]], dtype='int32')
A.dtype

dtype('int32')

##### Creation using numpy functions

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Null matrix of shape (3,3)
A = np.zeros((3,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Matrix filled with 1
A = np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Identity matrix
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Diagonal matrix
A = np.diag([2, -1, 3])
print(A)

[[ 2  0  0]
 [ 0 -1  0]
 [ 0  0  3]]


In [15]:
# Random matrix of shape (3,3)
A = np.random.randn(3,3)
print(A)

[[ 1.18259104  1.04732289 -2.36720482]
 [ 0.3760405  -0.16310772  0.25618718]
 [ 1.13913165 -0.31973278 -0.6998873 ]]


##### Reshaping

In [16]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Reshape
x.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Reshape creates a new reshaped object
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Resize reshapes inplace
x.resize((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Reshapes to the initial dimension
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# ravel and flaten do not modify the array (not inplace)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Concatenation

In [23]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [24]:
B = np.array([[5, 6], [7, 8]])
print(B)

[[5 6]
 [7 8]]


In [25]:
# Concatenate A and B vertically
print(np.concatenate((A, B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
# Concatenate A and B horizontally
print(np.concatenate((A, B), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
# Another way to concatenate vertically
print(np.vstack((A,B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
# Another way to concatenate horizontally
print(np.hstack((A,B)))

[[1 2 5 6]
 [3 4 7 8]]


#### Inexing and slicing

One dimensional numpy arrays can be sliced exactly as a list (Check TP0 for details).

In [29]:
A = np.array([[4,2,-2],[1,0,1],[6,-4,3]])
print(A)

[[ 4  2 -2]
 [ 1  0  1]
 [ 6 -4  3]]


In [30]:
# Access to a specific items
print(A[0,0])
print(A[1,2])

4
1


In [31]:
# Another way to access to items
print(A[0][0])
print(A[1][2])

4
1


In [32]:
# Access to a specific line
print(A[0,:])

[ 4  2 -2]


In [33]:
# Access to a specific column
print(A[:,0])

[4 1 6]


In [34]:
# Access to a specific bloc
print(A[1:,1:])

[[ 0  1]
 [-4  3]]


In [35]:
# Logical mask
print(A < 2)

[[False False  True]
 [ True  True  True]
 [False  True False]]


#### Algebraic operations

In [36]:
# Vectors definitions
x = np.array([1, 3])
y = np.array([4, 2])

# Matrices definitions
A = np.array([[1, -5], [-1, 4]])
B = np.array([[2, 1], [-4, 6]])

In [37]:
# Vector addition
print(x+y)

[5 5]


In [38]:
# Matrix addition
print(A+B)

[[ 3 -4]
 [-5 10]]


In [39]:
# Another way to perform addition (true fro both vectors and matrices)
print(np.add(A,B))

[[ 3 -4]
 [-5 10]]


In [40]:
# Subtraction
print(A-B)

[[-1 -6]
 [ 3 -2]]


In [41]:
# Another way to perform substraction
print(np.subtract(A,B))

[[-1 -6]
 [ 3 -2]]


In [42]:
# Scalar product
l = np.random.randn() # Generate a random scalar
print(l * x)
print(l * A)

[-0.2654147  -0.79624411]
[[-0.2654147   1.32707352]
 [ 0.2654147  -1.06165882]]


In [43]:
# Element wise product
print(A*B)

[[ 2 -5]
 [ 4 24]]


In [44]:
# Power (element wise power)
print(A**2)

[[ 1 25]
 [ 1 16]]


In [45]:
# Dot product
x.dot(y)

np.int64(10)

In [46]:
# Matrix product
print(A @ B)

[[ 22 -29]
 [-18  23]]


In [47]:
# Another way to perform matrix product
print(A.dot(B))

[[ 22 -29]
 [-18  23]]


In [48]:
# Matrix vector product
print(A @ x)

[-14  11]


In [49]:
# Another way to perform matrix vector product
print(A.dot(x))

[-14  11]


In [50]:
# Matrix transposition
print(A.T)

[[ 1 -1]
 [-5  4]]


In [51]:
# Compute the determinant of a matrix
print(np.linalg.det(A))

-1.0


In [52]:
# Compute the inverse of a matrix
M= np.random.randn(3,3) # Random matrix
A = M + M.T # To ensure invertibility
print(np.linalg.inv(A))

[[ 0.2549758  -0.40213895 -0.05075412]
 [-0.40213895  0.1628624  -0.01029562]
 [-0.05075412 -0.01029562  0.63742635]]


In [53]:
# Eigenvalues and Eigenvectors of a Matrix
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-5.05279684+0.j  1.68626568+0.j  1.51481095+0.j]
[[ 0.66625707+0.j  0.60146025+0.j -0.44084815+0.j]
 [ 0.74406735+0.j -0.57553676+0.j  0.33929517+0.j]
 [ 0.04965176+0.j  0.55407852+0.j  0.83098237+0.j]]


In [54]:
# Singular Value Decomposition (SVD) of a Matrix
U, S, V = np.linalg.svd(A)
print("U= ",U)
print("S= ",S)
print("V= ",V)

U=  [[-0.66625707  0.60146025 -0.44084815]
 [-0.74406735 -0.57553676  0.33929517]
 [-0.04965176  0.55407852  0.83098237]]
S=  [5.05279684 1.68626568 1.51481095]
V=  [[ 0.66625707  0.74406735  0.04965176]
 [ 0.60146025 -0.57553676  0.55407852]
 [-0.44084815  0.33929517  0.83098237]]


## Exercices

### Exercice 1

1. Create a matrix A and B of shape (2, 3), and a vector v of size 3, using the randn function from numpy.

In [55]:
# Answer
A = np.random.randn(2, 3)
B = np.random.randn(2, 3)
v = np.random.randn(3)

print("A =\n", A)
print("B =\n", B)
print("v =", v)


A =
 [[1.53761264 1.15065733 0.61818268]
 [0.63850121 0.47538462 0.43653134]]
B =
 [[ 0.16170392 -0.21500237 -1.70033225]
 [-0.22667224  0.32627858 -0.02298448]]
v = [0.8238911  0.2177104  0.58296215]


2. Compute the sum and the subtraction of matrices A and B.

In [56]:
# Answer
# Sum of A and B
sum_AB = A + B

# Subtraction of A and B
sub_AB = A - B

print("A + B =\n", sum_AB)
print("A - B =\n", sub_AB)


A + B =
 [[ 1.69931656  0.93565495 -1.08214957]
 [ 0.41182897  0.8016632   0.41354685]]
A - B =
 [[1.37590872 1.3656597  2.31851493]
 [0.86517344 0.14910604 0.45951582]]


3. Compute the product of λ=10 and the vector v.

In [57]:
# Answer
lambda_ = 10

product = lambda_ * v

print("10 * v =", product)


10 * v = [8.23891102 2.17710396 5.82962151]


4. Calculate the element-wise multiplication between A and B.

In [58]:
# Answer
element_wise = A * B

print("A * B =\n", element_wise)


A * B =
 [[ 0.24863799 -0.24739406 -1.05111595]
 [-0.1447305   0.15510782 -0.01003345]]


5. Calculate the product C between A and B.T.

In [59]:
# Answer
C = A @ B.T

print("C =\n", C)


C =
 [[-1.04987201e+00  1.26921343e-02]
 [-7.41208986e-01  3.43874772e-04]]


6. Calculate the product between A and v.

In [60]:
# Answer
result = A @ v

print("A @ v =", result)


A @ v = [1.87771254 0.88403288]


7. Give the detiminant of C.

In [61]:
# Answer
det_C = np.linalg.det(C)

print("det(C) =", det_C)


det(C) = 0.009046499470710992


8. Give J the Inverse of I, if I is inversible.

In [62]:
# Answer
I = np.random.randn(3, 3)

if np.linalg.det(I) != 0:
    J = np.linalg.inv(I)
    print("I =\n", I)
    print("J =\n", J)
else:
    print("I is not invertible")


I =
 [[-0.11544054  0.13365993  0.76543069]
 [-1.48387774 -0.3706485   0.65810338]
 [-0.88074415 -1.7352322  -0.27857886]]
J =
 [[ 0.86201529 -0.89368494  0.25729115]
 [-0.68741365  0.48894947 -0.73368166]
 [ 1.55649779 -0.22016418  0.16691997]]


9. Decompose the matrix I using eigendecomposition method.

In [63]:
# Answer
eigenvalues, eigenvectors = np.linalg.eig(I)

print("Eigenvalues =\n", eigenvalues)
print("Eigenvectors =\n", eigenvectors)


Eigenvalues =
 [ 0.50859994+0.j         -0.63663392+1.56042589j -0.63663392-1.56042589j]
Eigenvectors =
 [[-0.59010651+0.j          0.15476908+0.33466201j  0.15476908-0.33466201j]
 [ 0.56231102+0.j         -0.23269488+0.50188611j -0.23269488-0.50188611j]
 [-0.57929321+0.j         -0.74700154+0.j         -0.74700154-0.j        ]]


10. Decompose the matrix I using svd method

In [64]:
# Answer
U, S, Vt = np.linalg.svd(I)

print("U =\n", U)
print("S =\n", S)
print("Vt =\n", Vt)


U =
 [[-0.02147206 -0.49127015 -0.87074255]
 [-0.59676929 -0.69246903  0.40540482]
 [-0.80212553  0.52833729 -0.2783062 ]]
S =
 [2.27367177 1.36680029 0.46483331]
Vt =
 [[ 0.70127922  0.70819182 -0.08168111]
 [ 0.4528254  -0.53101276 -0.71622245]
 [-0.55059659  0.46528464 -0.69307546]]


### Exercice 2: Power iteration method

The objective of this excercice is to compute the eigenvector of a matrix associated to its largest eigenvector using the power iteration method: Given a squared matrix $A$ of shape $n\times n$ and a vector $x_0\in\mathbb{R}^n$, then the sequence of vectors $(x_k)_{k\in\mathbb{N}}$ defined as:
$$
x_{k+1}=\frac{Ax_k}{\Vert A x_k\Vert},
$$
converges to the largest eigenvector in absolute value (we admit this result).
  

1. Define a function ```power_iteration(A, x0, k)``` that returns $x_k$.



In [65]:
# Answer
def power_iteration(A, x0, k):
    x = x0
    
    for i in range(k):
        x = A @ x
        x = x / np.linalg.norm(x)
    
    return x


2. Using the function ```power_iteration```, compute the largest eigenvector of the matrix
$$
A = \begin{bmatrix} 0.5 & 0.5\\ 0.2 & 0.8 \end{bmatrix}
$$

In [66]:
# Answer

A = np.array([[0.5, 0.5],
              [0.2, 0.8]])

x0 = np.array([1, 0])

x = power_iteration(A, x0, 100)

print("Largest eigenvector:", x)

Largest eigenvector: [0.70710678 0.70710678]


3. Compute the eigenvalue associated to this vector.

***Indication:*** If $v$ is a normalized eigenvector of $A$, then its associated eigenvalue is given by $λ=Av⋅v$

In [67]:
# Answer
eigenvalue = (A @ x) @ x

print("Eigenvalue:", eigenvalue)


Eigenvalue: 1.0


4. Adapt the function ```power_iteration``` such that it allows to compute the largest eigenvalue with its associated eigenvector of a matrix given precision value.

In [68]:
# Answer
def power_iteration(A, x0, precision):
    x = x0 / np.linalg.norm(x0)

    while True:
        x_new = A @ x
        x_new = x_new / np.linalg.norm(x_new)

        if np.linalg.norm(x_new - x) < precision:
            break

        x = x_new

    eigenvalue = (A @ x_new) @ x_new

    return eigenvalue, x_new


A = np.array([[0.5, 0.5],
              [0.2, 0.8]])

x0 = np.array([1, 0])

eigenvalue, eigenvector = power_iteration(A, x0, 1e-6)

print("Largest eigenvalue:", eigenvalue)
print("Associated eigenvector:", eigenvector)


Largest eigenvalue: 0.9999999162979982
Associated eigenvector: [0.70710698 0.70710658]


5. Compare the execution times of the previous script and the numpy function for matrices of shape $n\times n$ with $n\in \{10, 100, 1000\}$   

In [69]:
import time

def power_iteration(A, x0, precision=1e-6, max_iter=1000):
    x = x0 / np.linalg.norm(x0)

    for _ in range(max_iter):
        x_new = A @ x
        x_new = x_new / np.linalg.norm(x_new)

        if np.linalg.norm(x_new - x) < precision:
            x = x_new
            break

        x = x_new

    eigenvalue = (A @ x) @ x
    return eigenvalue, x


for n in [10, 100, 1000]:
    A = np.random.randn(n, n)
    x0 = np.random.randn(n)

    # Power iteration
    start = time.time()
    eigenvalue, eigenvector = power_iteration(A, x0)
    power_time = time.time() - start

    # NumPy
    start = time.time()
    eigenvalues, eigenvectors = np.linalg.eig(A)
    numpy_time = time.time() - start

    print("n =", n)
    print("Power iteration:", power_time, "seconds")
    print("NumPy eig:", numpy_time, "seconds")
    print("--------------------")

n = 10
Power iteration: 0.015185832977294922 seconds
NumPy eig: 0.00014066696166992188 seconds
--------------------
n = 100
Power iteration: 0.013458967208862305 seconds
NumPy eig: 0.015504837036132812 seconds
--------------------
n = 1000
Power iteration: 0.3711376190185547 seconds
NumPy eig: 1.5043511390686035 seconds
--------------------


### Exercice 3

Let $A$ be a matrix and $b$ a vector defined by:

```
M = np.random.randn(3, 3)
A = M + M.T
b = np.random.rand(3)
```



Solve the linear system $Ax=b$ with two different methods

In [70]:
# Answer

M = np.random.randn(3, 3)
A = M + M.T
b = np.random.rand(3)

# Method 1: np.linalg.solve()
x1 = np.linalg.solve(A, b)

# Method 2: using the inverse of A
x2 = np.linalg.inv(A) @ b

print("Solution with np.linalg.solve():")
print(x1)

print("\nSolution with inverse:")
print(x2)

Solution with np.linalg.solve():
[ 0.16184888 -0.31932431  0.02533096]

Solution with inverse:
[ 0.16184888 -0.31932431  0.02533096]


### Exercice 4: Orthogonal Projections



The objectif of the exercice is to compute the orthogonal projection of a vector into a given subspace. We let be $x\in \mathbb{R}^{n}$, $E\subset\mathbb{R}^{n}$ a subspace of dimension $p$, and $B=\{e_1, ⋯,e_{p} \}$ an orthonormal basis of $E$. Then, the orthogonal projection of the vector $x$ on $E$ is given by
$$
p_E(x) = \sum_{i=1}^{p} <x,e_i>e_i
$$

In a more general case, given the matrix $A$ the projection matrix is given by
$$
P = A(A^tA)^{-1}A^t
$$
The projection matrix verifies the following properties:


1.   $P$ is a squared matrix.
2.   Symmetry $P^t=P$.
3.   $P$ is idempotent: $P^2= P$.


1. Define a function ```is_orthonormal(A)``` that takes as parameters the matrix $A$ of wich the columns corresponds to the basis vectors of the target subspace and returns  ```True``` if the basis is orthonormal ```False``` otherwise.

In [71]:
# Answer
def is_orthonormal(A):
    return np.allclose(A.T @ A, np.eye(A.shape[1]))


2. Define a function ```project(B,x)``` that takes as parameters a vector $x\in \mathbb{R}^{n}$ and ```B``` a list of vectors of the basis $B$.

In [72]:
# Answer
def project(B, x):
    projection = np.zeros_like(x, dtype=float)

    for e in B:
        projection += np.dot(x, e) * e

    return projection


3. Let $E$ the subspace spanned by the basis $B = \left\{\left(\frac{1}{\sqrt{2}},\frac{1}{\sqrt{2}},0\right)^t,\left(\frac{1}{\sqrt{3}},-\frac{1}{\sqrt{3}},\frac{1}{\sqrt{3}}\right)^t\right\}$. Verify that the basis is orthonormal.

In [73]:
# Answer
B = np.array([
    [1/np.sqrt(2),  1/np.sqrt(3)],
    [1/np.sqrt(2), -1/np.sqrt(3)],
    [0,             1/np.sqrt(3)]
])

print("Is B orthonormal?", is_orthonormal(B))


Is B orthonormal? True


4. Generate a three dimensional vector (i.e., n=3). And compute its projection on $E$.  

In [85]:
# Answer
B = [
    np.array([1/np.sqrt(2),  1/np.sqrt(2), 0]),
    np.array([1/np.sqrt(3), -1/np.sqrt(3), 1/np.sqrt(3)])
]

# Random vector x in R^3
x = np.random.randn(3)

# Projection of x onto E
proj_x = project(B, x)

print("x = ", x)
print("Projection of x on E = ", proj_x)


x =  [-1.26851043  0.12518547 -0.07550641]
Projection of x on E =  [-1.06139658 -0.08192838 -0.4897341 ]


5. Let be $E$ the subspace spanned by $B=\left\{ (0,1,1)^t,(1,-1,1)^t \right\}$, and $x=(1,2,-1)^t$. Compute the projection matrix $P$ and verify numerically that it satisfies the three properties listed above.

In [86]:
# Answer
B = np.array([
    [0, 1],
    [1, -1],
    [1, 1]
])

x = np.array([1, 2, -1])

# Projection matrix P = B(B^T B)^(-1)B^T
P = B @ np.linalg.inv(B.T @ B) @ B.T

print("Projection matrix P =")
print(P)

# Verify the three properties
print("\n1. P is squared:", P.shape[0] == P.shape[1])

print("2. P is symmetric:", np.allclose(P.T, P))

print("3. P is idempotent:", np.allclose(P @ P, P))


Projection matrix P =
[[ 0.33333333 -0.33333333  0.33333333]
 [-0.33333333  0.83333333  0.16666667]
 [ 0.33333333  0.16666667  0.83333333]]

1. P is squared: True
2. P is symmetric: True
3. P is idempotent: True


6. Compute the projection of $x$ on $E$.

In [87]:
# Answer
projection = P @ x

print("Projection of x on E =")
print(projection)


Projection of x on E =
[-0.66666667  1.16666667 -0.16666667]


### Exercise 5: Diagonalization of symmetric Matrices


The objective of this exercice is to complement a Python program that demonstrates the diagonalization of a symmetric matrix:

1. Generate a random symmetric matrix of a specified size.<br>



In [88]:
# Answer

n = 3

M = np.random.randn(n, n)
A = (M + M.T) / 2

print("Symmetric matrix A =")
print(A)


Symmetric matrix A =
[[ 0.80294802  1.15214055  0.91010618]
 [ 1.15214055 -0.28669579  0.76110059]
 [ 0.91010618  0.76110059  0.45151882]]


2. Compute the eigenvalues and eigenvectors of the symmetric matrix.

In [89]:
# Answer
eigenvalues, eigenvectors = np.linalg.eigh(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[-1.04181648 -0.27898524  2.28857278]

Eigenvectors:
[[ 0.46459743 -0.54647328 -0.69678991]
 [-0.87082199 -0.13917298 -0.47148694]
 [ 0.16068069  0.82583161 -0.54054036]]


3. Verify that the eigenvectors are orthogonal.

In [90]:
# Answer
print(np.allclose(eigenvectors.T @ eigenvectors, np.eye(A.shape[0])))


True


4. Construct a diagonal matrix using the eigenvalues.

In [91]:
# Answer
D = np.diag(eigenvalues)

print("Diagonal matrix D:")
print(D)


Diagonal matrix D:
[[-1.04181648  0.          0.        ]
 [ 0.         -0.27898524  0.        ]
 [ 0.          0.          2.28857278]]


5. Reconstruct the original matrix using eigenvectors and the diagonal matrix.

In [92]:
# Answer
A_reconstructed = eigenvectors @ D @ eigenvectors.T

print("Reconstructed matrix:")
print(A_reconstructed)

print("\nIs it equal to the original matrix?")
print(np.allclose(A, A_reconstructed))


Reconstructed matrix:
[[ 0.80294802  1.15214055  0.91010618]
 [ 1.15214055 -0.28669579  0.76110059]
 [ 0.91010618  0.76110059  0.45151882]]

Is it equal to the original matrix?
True


### Exercise 6:
1. Define a class Squared_matrix that inherits from the class ```np.matrix``` with the attribute values which corresponds to the squared matrix, and a constructor that instanciates the classe (it should return an error message if the matrix is not squared) and an ```__str()__``` that prints the matrix.

In [93]:
# Answer
class Squared_matrix(np.matrix):
    def __new__(cls, values):
        values = np.asarray(values)
        
        if values.shape[0] != values.shape[1]:
            raise ValueError("Error: the matrix is not squared")
        
        return np.matrix(values).view(cls)

    def __str__(self):
        return str(self.values if hasattr(self, 'values') else np.asarray(self))


# Exemple
A = Squared_matrix([[1, 2], [3, 4]])

print(A)


[[1 2]
 [3 4]]


2. Define a method:
* ```rank()``` that returns the rank of the matrix.  
* ```is_invertible```that returns a boolean (```True``` if the matrix is invertible ```False``` otherwise).
* ```inverse()``` that returns the inverse of the matrix when possible.
* ```eigenvalues()``` and ```eigenvectors``` that return the eigenvalues and eigenvectors of the matrix.

In [94]:
# Answer
class Squared_matrix(np.matrix):
    def __new__(cls, values):
        values = np.asarray(values)
        
        if values.shape[0] != values.shape[1]:
            raise ValueError("Error: the matrix is not squared")
        
        obj = np.matrix(values).view(cls)
        obj.values = values
        return obj

    def __str__(self):
        return str(self.values)

    def rank(self):
        return np.linalg.matrix_rank(self.values)

    def is_invertible(self):
        return np.linalg.det(self.values) != 0

    def inverse(self):
        if not self.is_invertible():
            raise ValueError("Error: the matrix is not invertible")
        return np.linalg.inv(self.values)

    def eigenvalues(self):
        return np.linalg.eigvals(self.values)

    def eigenvectors(self):
        return np.linalg.eig(self.values)[1]


# Exemple
A = Squared_matrix([[1, 2], [3, 4]])

print("Matrix:")
print(A)

print("Rank:", A.rank())
print("Is invertible:", A.is_invertible())
print("Inverse:")
print(A.inverse())
print("Eigenvalues:", A.eigenvalues())
print("Eigenvectors:")
print(A.eigenvectors())


Matrix:
[[1 2]
 [3 4]]
Rank: 2
Is invertible: True
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132+0.j  5.37228132+0.j]
Eigenvectors:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


3. Given a squared matrix $A$, we recall the definition of some norms:

$$
\begin{align*}
&||A||_F \, = \sqrt{\sum_{i=1}^n\sum_{j=1}^n a^2_{i,j}} = \sqrt{tr(A^tA)},  \\
&||A||_1 \,\, = \max_{1\leq j\leq n} \sum_{i=1}^{n}|a_{i,j}|, \\
&||A||_2 \,\, = \sqrt{\rho(A^tA)}, \\
&||A||_\infty = \max_{1\leq i\leq n} \sum_{j=1}^{n}|a_{i,j}|,
\end{align*}
$$
where $\rho(\cdot)$ design the spectral radius, i.e., the largest (in absolute value) eigenvalue of a matrix. Define the method ```norm_f(ind)``` that returns the norm given the indice ```ind``` (the indice is a string with possible values: ```"F"```,```"1"```,```"2"```, and ```"inf"```).


In [95]:
# Answer
class Squared_matrix(np.matrix):
    def __new__(cls, values):
        values = np.asarray(values)

        if values.shape[0] != values.shape[1]:
            raise ValueError("Error: the matrix is not squared")

        obj = np.matrix(values).view(cls)
        obj.values = values
        return obj

    def __str__(self):
        return str(self.values)

    def rank(self):
        return np.linalg.matrix_rank(self.values)

    def is_invertible(self):
        return np.linalg.det(self.values) != 0

    def inverse(self):
        if not self.is_invertible():
            raise ValueError("Error: the matrix is not invertible")
        return np.linalg.inv(self.values)

    def eigenvalues(self):
        return np.linalg.eigvals(self.values)

    def eigenvectors(self):
        return np.linalg.eig(self.values)[1]

    def norm_f(self, ind):
        if ind == "F":
            return np.linalg.norm(self.values, 'fro')

        elif ind == "1":
            return np.linalg.norm(self.values, 1)

        elif ind == "2":
            return np.linalg.norm(self.values, 2)

        elif ind == "inf":
            return np.linalg.norm(self.values, np.inf)

        else:
            raise ValueError("Error: invalid norm. Use 'F', '1', '2' or 'inf'")


# Exemple
A = Squared_matrix([[1, 2], [3, 4]])

print("Norm F :", A.norm_f("F"))
print("Norm 1 :", A.norm_f("1"))
print("Norm 2 :", A.norm_f("2"))
print("Norm inf :", A.norm_f("inf"))



Norm F : 5.477225575051661
Norm 1 : 6.0
Norm 2 : 5.464985704219043
Norm inf : 7.0
